chore: check token

diff --git a/.github/workflows/vercel.yaml b/.github/workflows/vercel.yaml
--- a/.github/workflows/vercel.yaml
+++ b/.github/workflows/vercel.yaml
@@ -51,6 +51,16 @@ jobs:
       #   with:
       #     ## limits ssh access and adds the ssh public key for the user which triggered the workflow
       #     limit-access-to-actor: true
+      - name: "Check VERCEL_TOKEN"
+        env:
+          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
+        run: |
+          if [ -z "$VERCEL_TOKEN" ]; then
+            echo "::error::VERCEL_TOKEN is empty or not set"
+            exit 1
+          else
+            echo "VERCEL_TOKEN is set"
+          fi
       - name: "Deploy vite test-app site to Vercel"
         env:
           # Domain: experience-builder-test-app.colorfuldemo.com
@@ -82,7 +92,7 @@ jobs:
             vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
             vercel build --prod --token="$VERCEL_TOKEN"
             vercel deploy --prod --prebuilt --token="$VERCEL_TOKEN"
-          else
+          else            
             vercel pull --yes --environment=preview --token="$VERCEL_TOKEN"
             vercel build --token="$VERCEL_TOKEN"
             vercel deploy --prebuilt --token="$VERCEL_TOKEN"
